FROM node:20-alpine

WORKDIR /app

ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="pk_test_51Qo09pKpgF9iR45Xgz1wmynfHzoEE124t9yPn06ijZPZiBCenvFPANoAg8RFPL3AhepGP0BbPeCkQeF1upXk7UcL00kosx6mHF"
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}

COPY web/package*.json ./

RUN npm install

COPY web ./

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]