apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
# stringData allows you to write the password in plain text
# Kubernetes will base64 encode it automatically for you.
stringData:
  username: guest
  password: guest